version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt -t .
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket my-cloudformation-artifacts --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
